### ISSUE TITLE
Missing item-template and items-sample

### ISSUE THREAD

**Issue by Hequinoxe** [SvenWerlen/fvtt-data-toolbox#11]
Not sure if this is a missing feature or the droplist include a type that is not yet implemented but I did not see any template or samples to import items. Thanks

**Comment by SvenWerlen** [comment]
Hi, 
It is implemented but the module doesn't provide any sample for testing it. Do you have a specific use case for any system ? If not, I could provide an example based on pathfinder 1 if it helps you.

**Comment by Hequinoxe** [comment]
Hi, Thanks for the prompt reply. I would like to add items in dnd 5e (ex: books, valuables) based on lists (I bought a few tables but I would like to have them as items and not texts in rolltables). I attached a csv of the headers I would like to add. I expect I am not using the correct headers but hopefully they should be evocative enough.

[item-sample.zip](https://github.com/SvenWerlen/fvtt-data-toolbox/files/6141370/item-sample.zip)

**Comment by SvenWerlen** [comment]
A new version `1.7.0` of Data Toolbox has been published. It contains a sample for item for DnD 5e. 
I hope that it fullfills your needs.

**Comment by SvenWerlen** [comment]
![image](https://user-images.githubusercontent.com/938060/111554304-71262b80-875c-11eb-9440-d4f7704ccb73.png)

**Comment by Hequinoxe** [comment]
Hi,

Just to let you know that it works like a charm.

Thank you!

**Comment by SvenWerlen** [comment]
Thanks for the feedback. Glad that it worked. Feel free to contact me back.
