### ISSUE TITLE
Let's Contribute - Journal error

### ISSUE THREAD

**Issue by jbhuddleston** [SvenWerlen/fvtt-data-toolbox#12]
Attempting to import a submitted journal entry, results in "Error: You must define a valid Item type".

Also, I am not sure how to submit actors at this point. Perhaps it is not yet supported?

Items are working fine, thanks for all the hard work,
James

**Comment by SvenWerlen** [comment]
I tested with a journal article and it worked in my case. 

Can you provide more details? Is the error from the console (F12) or a notification?
Which compendium?

**Comment by jbhuddleston** [comment]
The error showed up in a notification and on the console.
The compendium was my Dropbox for VsD Journals (vsd-journal-dropbox.db).
I will post another Journal there that gives me the error so you can look at it at your end.
Done. The journal in there now throws the error.

**Comment by SvenWerlen** [comment]
Fixed in `1.9.1+`
