### ISSUE TITLE
PC Title Bar Action Buttons

### ISSUE THREAD

**Issue by HippyCraig** [SvenWerlen/fvtt-data-toolbox#13]
There seems to be some overlap in the buttons in the title bar window of a PC Sheet.  Your "Contribute" button is overlapping all the other buttons in the title bar.  See below:

![image](https://user-images.githubusercontent.com/17074456/113513798-549a3980-9539-11eb-9f69-65d8b17ec057.png)

**Comment by SvenWerlen** [comment]
Mmm... it looks like the window was not large enough for all options. Can you confirm?
I will then probably have to make it optional (icon only, icon + text or icon inside window as before)

**Comment by HippyCraig** [comment]
I have a 4K screen with 150% scaling enable if that help. Also resizing the window doesn’t help

**Comment by SvenWerlen** [comment]
Unfortunately, I'm not able to reproduce. Which system do you use ? Can you reproduce it for items too or only for actor sheets?
It should be rendered like on this screenshot
![image](https://user-images.githubusercontent.com/938060/114256487-87a05b00-9987-11eb-9451-9cf106de1f4c.png)

**Comment by HippyCraig** [comment]
Im using DND 5e  This also happens with Items as well, even if I expand the window, I just kept it small for the screen shot.

![image](https://user-images.githubusercontent.com/17074456/114308014-540d2000-9ab0-11eb-842f-f97c3cc36f8c.png)

**Comment by SvenWerlen** [comment]
Well, I'm still not able to reproduce this error. I installed the modules you have (PopOut, DAE and GM Notes). But everything fits. I tested on native application, Firefox and Chrome browser. It's really strange that even when expanding the window, the issue remains. Which browser do you use ? Are you on Forge ?
If I cannot find the issue, I'll probably propose a configuration to hide it.
![image](https://user-images.githubusercontent.com/938060/115159998-e5a60000-a063-11eb-9795-05be8dac029e.png)

**Comment by HippyCraig** [comment]
Chrome and I host it on a windows 10 VM in Azure.  If I am the only one with the issue then it could be just my install I can try removing it and re-adding it.

**Comment by kenpoh01** [comment]
I am having a similar problem with Feats (items).  I have to constantly resize the window in order for the "close" option to show up.
![image](https://user-images.githubusercontent.com/36082436/116797766-7a264e80-aab7-11eb-9746-f919f7434fdc.png)

**Comment by SvenWerlen** [comment]
It's been a long time I've not been supporting this module any more.
I recently clean it up to make it working for V9
I removed the "Contribute" part of the module (not supporting it anymore). This is then fixed.
