### ISSUE TITLE
this.extensions is undefined

### ISSUE THREAD

**Issue by DanieleSuppo** [SvenWerlen/fvtt-data-toolbox#14]
When I try to upload a file (both csv and json), nothing happens.
The console shows the error "this.extension is undefined"

Game System: Coriolis
See image in attachment

Regards

![immagine](https://user-images.githubusercontent.com/2264815/116795498-b36db700-aad5-11eb-8b95-a35b3bc8c0de.png)

**Comment by SvenWerlen** [comment]
I recently cleanup this module to make it work on V9. I tested on game system Coriolis and it worked as expected. 
I'm closing this issue but feel free to re-open it if you can reproduce on V9.
