### ISSUE TITLE
Disclose what is submitted

### ISSUE THREAD

**Issue by mkahvi** [SvenWerlen/fvtt-data-toolbox#16]
I would like the submission to disclose what exactly is being submitted, and maybe show a diff of the changes I've made.

I sometimes have doubts I'm sending a proper update or that my update might have something in it that I don't think it should have (e.g. data injected by other modules) and end up worrying I might just clutter the system with useless submissions. This has led me to just avoid making any.

**Comment by SvenWerlen** [comment]
As mentionned in https://github.com/SvenWerlen/fvtt-data-toolbox/issues/22#issuecomment-1013918159 , I'm stopped maintaining and supporting Let's Contribute part of the module.
