### ISSUE TITLE
Special character names are not shown in the review macro

### ISSUE THREAD

**Issue by BrotherSharper** [SvenWerlen/fvtt-data-toolbox#17]
When LetsContribute.showReviewerUI() is ran, item names containing special characters are not shown, and instead you only get ????s as seen in the image.

![image](https://user-images.githubusercontent.com/41280723/123531095-8f78cb80-d73c-11eb-91b8-1848732d1251.png)}}

Here is a json file of a class item with Japanese name in case somebody wants to tackle this.

[fvtt-Item-クラフター.zip](https://github.com/SvenWerlen/fvtt-data-toolbox/files/6720943/fvtt-Item-.zip)

**Comment by SvenWerlen** [comment]
Hi, I'm very sorry but I decided to stop maintaining and supporting the Let's contribute part of the module. See:
https://github.com/SvenWerlen/fvtt-data-toolbox/issues/22#issuecomment-1013918159
