### ISSUE TITLE
Fail to import into compendium using fvtt 0.87  yze-coriolis 2.21

### ISSUE THREAD

**Issue by karnowski1972** [SvenWerlen/fvtt-data-toolbox#18]
Using a simple csv with only two columns and a json Item file I tried to start importing some injuries into a test compendium. However, nothing happened. Looking into the console I found the following error message:

data-toolbox.js:138 Uncaught (in promise) TypeError: Compendium.create is not a function
    at GenerateCompendiumDialog._generate (data-toolbox.js:138)
_generate @ data-toolbox.js:138
async function (async)
_generate @ data-toolbox.js:85
callback @ data-toolbox.js:20
submit @ foundry.js:20410
_onClickButton @ foundry.js:20373
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

Not sure what the cause for this issue is?

**Comment by DanielRonnstam** [comment]
I have exactly the same issue, nothing happens after I create compendium. The same setup fvtt 0.8.7 yze-coriolis 2.21. 

Also, when I try to upload the csv and template file, I can't upload a file in the popup to the server. I have to go into the server from elsewhere and manually upload the files before I can use them in the popup.

I have tried Find the Culprit, its not a conflict.

A question... how long can the strings be? I want to use this for creating journal articles, so the texts can be long.

**Comment by DanielRonnstam** [comment]
Please fix this bug as soon as you can! thanks. This add-on saves so much preptime.

**Comment by SvenWerlen** [comment]
Support for 0.8.x+ has been added. I need more time for investigating the upload file issue.

**Comment by SvenWerlen** [comment]
Ok, this seems to be a bug in FoundryVTT which only supports "image", "video" and "imagevideo" as types. If I specify one of them, you won't be able to select `json` file nor `csv`. If I leave it undefined, you get that bug.

**Comment by DanielRonnstam** [comment]
ok so the only solution is to upload to the server data folder workaround, and then choose the files there. I will try now.

**Comment by zgsuppo** [comment]
Just to clean a little, you can merge this issue with the one I already opened about upload:
https://github.com/SvenWerlen/fvtt-data-toolbox/issues/14

**Comment by SvenWerlen** [comment]
This bug should be fixed (at least in recent V9). Feel free to reopen it if it's not the case.
