### ISSUE TITLE
BUG: Fails to import if compendium already exists

### ISSUE THREAD

**Issue by sharkbruhaha** [SvenWerlen/fvtt-data-toolbox#19]
Previous to v8 of Foundry, the mod would update/remake the compendium with the same name with the new imported csv conversion. Now it is tossing an error saying:
![image](https://user-images.githubusercontent.com/44031572/124372118-6386aa00-dc56-11eb-8a22-01563a8b9b55.png)

**Comment by SvenWerlen** [comment]
I finally spend some time on cleaning this module and making it compatible with V9. It's fixed as part of the latest release `2.1.0+`
