### ISSUE TITLE
Can't import Iron Gods Part 2 - Hellion

### ISSUE THREAD

**Issue by adventuremagic123** [SvenWerlen/fvtt-data-toolbox#2]
This stat block can't be imported for some reason.  It's the most complex in the Iron Gods Part 2 book.

Hellion      CR 6/MR 4
XP 2,400
Hellion
CE Medium artificial intelligence (mythic)
Init +6/-14, dual initiative; Senses Perception +16
--------------------
Defense
--------------------
AC 14, touch 10, flat-footed 14 (+4 natural)
hp 1 (+1)
Fort +2, Ref +2, Will +11
--------------------
Offense
--------------------
Speed 0 ft.
Space 0 ft.; Reach 0 ft.
Special Attacks mythic power (4/day, surge +1d8)
Spell-Like Abilities (CL 8th; concentration +12)
   1/day—align weapon (chaos or evil only), animate rope, chaos hammer (DC 18), command (DC 15), confusion (DC 18), dispel magic, entropic shield, lesser confusion (DC 15), magic circle against good, magic circle against law, minor creation, moonstruck[APG] (DC 18), protection from good, protection from law, rage, stone shape, touch of idiocy, unholy blight (DC 18), wood shape (DC 16)
--------------------
Statistics
--------------------
Str —, Dex —, Con —, Int 14, Wis 17, Cha 19
Base Atk +6; CMB +6; CMD 16
Feats Alertness, Combat Expertise, Improved Initiative[M], Iron Will[M], Technologist
Skills Bluff +15, Disable Device +11, Intimidate +12, Knowledge (engineering) +13, Knowledge (local) +10, Knowledge (religion) +10, Perception +16, Sense Motive +13
Languages Androffan, Orc
SQ impart mythic traits, inherited divinity
--------------------
Special Abilities
--------------------
Combat Expertise +/-2 Bonus to AC in exchange for an equal penalty to attack.
Dual Initiative (Ex) You act a second time each round at -20 from your normal initiative
Impart Mythic Traits (Ex) Hellion has no hit points or natural armor, but when it inhabits a robot, its mythic nature grants the robot a +4 bonus to the robot’s natural armor and an additional 40 hit points. Robots it inhabits do not gain DR/epic, but they do lose their vul
Improved Initiative [Mythic] When rolling initiative, use 1 power to treat the roll as a natural 20.
Inherited Divinity (Su) Hellion can grant divine spells to those who follow its cause, allowing them to select Hellion as their deity for the purposes of determining their spells and domains. Creatures that gain spells from Hellion don’t receive any spells per day of leve
Iron Will [Mythic] Roll Will save vs. spells, Sp, or Su abilities from non-mythic foe twice (take higher).
Spell-Like Abilities (Sp) Hellion can cast a few of the spells it grants from its domains as spell-like abilities, provided it has a conduit through which it can manifest the magic. In this adventure, appropriate conduits include its robot chassis and any of the monitors in t
Surge (1d8) Spend a use of mythic power to add the roll of a die to a d20 you just rolled
Technologist You are familiar with the basic mechanics of technology.

Benefit: You are considered to be trained in any skill used against a technology-based subject. If the skill in question requires training to use even against non-technological su
--------------------
When the AI Unity took a portion of its own programming and downloaded it into an empty processor, it created a pared-down version of itself, hoping to utilize this “child” AI as a herald and minion of sorts beyond the confines of Silver Mount. Unity placed this new AI into a large arachnid robot and sent it out into the world on a test run, intending to transfer the AI into a more powerful annihilator robot if it proved successful, but as soon as the arachnid robot set foot outside the ruins of Divinity, it gained free will. Its moment of ascension and realization that its source code, Unity, wanted to use it as a slave were more than enough to encourage its flight from central Numeria. In time, the AI came to Scrapwall, where it dug in to consider its options.

In the centuries since its arrival in Scrapwall, Hellion has done more than just give itself a name. Taking on a ferocious persona to intimidate its worshipers, the AI likens itself to a powerful fiend, although it doesn’t quite fully grasp the differences between devils and demons or the philosophical differences between Hell and the Abyss. It simply uses fiendish imagery when speaking to its followers via its monitors—this, coupled with the deep, emotionless drone of its voice has done wonders to inspire fear and adoration in those who see it as a god.
--------------------
Additional Details
--------------------
Campaign Role Hellion serves as a vision of things to come, a preview of the primary villain of the Adventure Path. By fighting against Hellion, the PCs unknowingly prepare themselves for the dangers they will eventually face in Silver Mount in the last installment of the Iron Gods Adventure Path. The PCs can also glean significant information about Divinity, Unity, and other key plot points from the way Hellion interacts with or taunts the PCs (see page 37 of the adventure).

Canny PCs might realize that despite its destructive and cruel nature, Hellion wants the same thing the PCs do in the end—the destruction of Unity. As such, should the PCs realize that the true danger facing Numeria is Hellion’s creator, they may try to ally with Hellion and recruit it to their cause. Unfortunately, this plan is fraught with peril, for Hellion never truly gained a full personality of its own—its intelligence is, essentially, crippled with madness and obsession. It is incapable of seeing anything else, be it biological or mechanical, as an ally or equal, and any alliance forged with the mad AI should fall apart quickly when Hellion attempts to murder its so-called “friends” in a simple fit of cruelty. In this way, you can limit the amount of information Hellion imparts to the PCs—they should learn that Unity is their true concern, but shouldn’t learn much about Silver Mount itself from Unity’s “child,” Hellion.

If Hellion escapes this adventure intact in its robotic chassis, it can become a recurring villain. In this case, Hellion should precede the PCs and attempt to find Casandalee before them, abandoning its greater plans for awakening the excavator for its secondary goal to absorb its “sister’s” memories to augment its powers. See the fourth installment of Iron Gods, “Valley of the Brain Collectors,” for information on how to incorporate this plot twist into the campaign.
Interrogating Hellion As the PCs explore the excavator, they’ll be confronted time and time again by Hellion via the numerous monitors and holographic projectors found throughout the location. When Hellion confronts the PCs, the overconfident, bombastic AI takes on an antagonistic and insulting air, calling the PCs “unfortunate biological accidents,” “curiously sentient apes,” “blood-filled puppets,” and the like. It may invite the PCs to simply turn around and abandon their foolish opposition to superior intellects, and it may threaten them with all manner of bodily harm, such as the boiling of their tissues from their brittle bones or the scraping of all last remnants of thought and self from their brutish skulls. The goal is to make the PCs eager to defeat Hellion, and to establish the AI as both mad and arrogant.

Yet canny PCs can still get tidbits of information out of Hellion if they ask about certain topics; the AI is unconcerned about the possibility of their success, after all, although once the PCs have killed most of its Lords of Rust, Hellion may finally (and likely too late) realize it’s not as invulnerable as it had assumed. 

If the PCs ask about Silver Mount, Unity, or related subjects, Hellion’s anger increases as it boasts that Silver Mount is its rightful throne, that Unity is a parasite and mere collection of glitches and programming errors that fancies itself the master of Divinity (the use of the word has a double meaning, of course, that the PCs may not immediately understand), and that it, Hellion, shall soon rule therein. If the PCs ask about Casandalee, Hellion grows quiet, then demands to know more about its “wayward sister.” It may even ask, “You have been, then, to Iadenveigh? Does she still live?” As soon as it realizes the PCs don’t know much about her, though, Hellion shrieks in frustration and either attacks with its spell-like abilities or simply goes silent.

At your option, Hellion can reveal other clues as well, depending on what the PCs ask.

**Comment by SvenWerlen** [comment]
I'm not sure if you reported this issue on the right project. It looks like it's related to [StatBlock Converter Module](https://github.com/Lavaeolous/PF1-StatBlock-Converter-Module).

If it is really you intend to report it here, can you please share the CSV and template files that you use?

**Comment by adventuremagic123** [comment]
Create for wrong project.  Sorry.
