### ISSUE TITLE
Consideration for windows users in other countries and booleans

### ISSUE THREAD

**Issue by javur1** [SvenWerlen/fvtt-data-toolbox#20]
Be careful with boleans and your region and country specifications for windows. 

Csv in my country is separated in semicolons ; and not commas and you have to make sure they are commas so you can use this.

Next, for booleans "true/flase" excel sometimes formats them in all caps (TRUE/FALSE) so you must change that too.

You can solve both things with the replace tool on the notepad or notepad++.

**Comment by javur1** [comment]
If you don't take these considerations, the compendium is created but it's empty. Checking the console shows that the replacements are changed from (for example) "{{Name}}" to undefined.

**Comment by SvenWerlen** [comment]
Cleanup of old issues. 
Feel free to reopen it if it's still an issue for you
