### ISSUE TITLE
Importing NPC with "Small" size doesn't work

### ISSUE THREAD

**Issue by kenpoh01** [SvenWerlen/fvtt-data-toolbox#23]
I'm on V9 of foundry and was able to import some NPCs yesterday.  I had to change one thing in my Template for the images to show up correctly but almost everything else worked fine.  The only issue I had was when the entry for a "small" NPC was reached.  For some reason, I received an error on that line (something to do with "width", sorry, I didn't screenshot it).  However, when I changed the size of the creature to anything else, it worked fine.  Not sure if anyone else is having this problem.

**Comment by kenpoh01** [comment]
Oh, one other thing, my newly generated compendium wouldn't show up until I reloaded Foundry.

**Comment by SvenWerlen** [comment]
I released a new version (tested on V9) and I wasn't able to reproduce this issue with the sample files. Could you please test with the new release and report if this is still an issue? I'll close it but feel free to reopen it.
