### ISSUE TITLE
.csv files not showing in list

### ISSUE THREAD

**Issue by llothos** [SvenWerlen/fvtt-data-toolbox#26]
with version 9 build 255 I no longer see .csv files in the list of files to import my template, I navigate to the folder and It only shows the .json files 3 even though there are definitely .csv files as well. I've tried both the Star Wars (FFG) system and Sentinels one. I've previously imported a lot for my Genesys game (in the start wars system) and worked wonderfully but now I'm working on adding some of the Sentinels information and even if I try to manually load the file it tells me it's an unsupported file type error.

**Comment by llothos** [comment]
Others on discord confirmed they are having same issue.

**Comment by DanieleSuppo** [comment]
I can confirm I'm having the same problem

**Comment by DanieleSuppo** [comment]
Quick workaround for anyone having the same problem: renaming the csv in txt, it shows up and the import will work.

**Comment by llothos** [comment]
I was also able to change it to .xml and it also worked fine.

**Comment by DanieleSuppo** [comment]
Opened an issue on Foundry:
https://gitlab.com/foundrynet/foundryvtt/-/issues/6881

**Comment by SvenWerlen** [comment]
Thanks all for reporting it and sorry for my late answer. I'll check it but according to your messages, it's probably due to a change in FilePicker API. Should I rename the files to .txt or wait for V10 to fix it?

**Comment by llothos** [comment]
Both xlm and txt seem to have been confirmed as working.
