### ISSUE TITLE
Import csv into a sub folder in the Data-Toolbox compendium

### ISSUE THREAD

**Issue by mattbell69** [SvenWerlen/fvtt-data-toolbox#27]
Would be good to be able to provide a name for a Folder that all the Imported objects would go in. Then you can Import the Folder and it would appear in Items, for example, under that Folder name. At the moment they are at root and you have to move them all.

Unless you can do this and I've missed it.

**Comment by FuzzySadist** [comment]
+1

**Comment by SvenWerlen** [comment]
I'm not sure I understand this feature request.
Compendiums don't have folders. Do you use a module like "Compendium Folders"? Or do you want the items generated in the compendiums to get imported into a specific folder?

**Comment by RinVindor** [comment]
So now that Foundry V11 has released, Compendiums have folders natively (the mod Compendium Folders has obviously ceased development for future versions). Now this would be an amazing addition for Data Toolbox to have.

**Comment by SvenWerlen** [comment]
Supported since `2.5.0`
