### ISSUE TITLE
Support for more characters

### ISSUE THREAD

**Issue by RinVindor** [SvenWerlen/fvtt-data-toolbox#28]
Some text like apostrophes, • and the like are currently rendered with � instead, so it'd be wonderful to have extended character support.

**Comment by RinVindor** [comment]
I know its been awhile since I posted the suggestion, if there is any way I could get an answer on this I'd appreciate it greatly, I'd certainly be willing to pay for such an update.

**Comment by SvenWerlen** [comment]
Hi @RinVindor,
Did you try to save your files using utf-8? This might be the issue.
If this is not the case, can you share your files and I'll troubleshoot them.

**Comment by RinVindor** [comment]
Yeah its saved on utf-8. When I open them up in Libre Office it also is the default option when opening them.

![image](https://user-images.githubusercontent.com/12647469/217997366-e0144ee5-f314-45c6-a971-ef9a860cabe3.png)

[discipline power-vampire.csv](https://github.com/SvenWerlen/fvtt-data-toolbox/files/10703567/discipline.power-vampire.csv)

**Comment by SvenWerlen** [comment]
I tested your CSV on my end and it worked properly. 
I'm on Linux and my entire system is configured with utf-8. I suspect that FoundryVTT might use the default locale of your OS, which is probably not utf-8. Could you check?

![image](https://user-images.githubusercontent.com/938060/218611387-6862e4e9-9a82-491d-ab31-93d09c6caa33.png)

**Comment by RinVindor** [comment]
Hey Sven, I checked myself again and now its fine, weird but I also haven't tried to import anything since V9 of Foundry. Welp consider this issue closed 😂

**Comment by SvenWerlen** [comment]
Thanks for confirming this!
