### ISSUE TITLE
Price and Damage do not populate on the item. 

### ISSUE THREAD

**Issue by jephkay23** [SvenWerlen/fvtt-data-toolbox#34]
Price and Damage do not populate on the item.  Damage always comes through the import as 1d6, no matter the value on the CSV.

**Comment by Lyinggod** [comment]
Perhaps if included the source file and template, the version of foundry, the version of the mod, and actual information such as any messages in the console, your issue might be able to be addressed. As it is, there is nothing here for anyone to work with.

**Comment by SvenWerlen** [comment]
@Lyinggod +1

@jephkay23 : could you please share the CSV and template you use? Data Toolbox is tricky to use and a missing quote or a space could lead to such a result. If it comes as `1d6` it's probably the default value.

**Comment by SvenWerlen** [comment]
I close this (no response)
