### ISSUE TITLE
Item import issue V11

### ISSUE THREAD

**Issue by R0gu3P403n1x** [SvenWerlen/fvtt-data-toolbox#39]
I am attempting to use the item template provided with data toolbox to import some items.  If this works, I will customize the template a bit, but that is down the road.  Every time I try, I get the following error:

Uncaught (in promise) Error: undefined. SyntaxError: Unexpected token 'u', ..."uantity": undefined,"... is not valid JSON
[Detected 1 package: data-toolbox]
    at GenerateCompendiumDialog._generate (data-toolbox.js:200:15)

I am unsure where the error is.  Please help.  My csv file has 347 items in it!

**Comment by SvenWerlen** [comment]
Hi there,
Could you please share the CSV and template you use? 
This will help me reproduce the issue and help you

**Comment by R0gu3P403n1x** [comment]
it was entirely a formatting issue on my part.  I did not have quotes where
I needed them.  So it was never a problem on your end at all!  Thank you
for getting in touch though.

**Comment by SvenWerlen** [comment]
Excellent, thanks for your reply
