### ISSUE TITLE
Feature Request: User-named compendium

### ISSUE THREAD

**Issue by jp-larose** [SvenWerlen/fvtt-data-toolbox#6]
Can you add a feature where the user can add the name of the compendium being generated?  Right now "toolbox-data" seems to be hardcoded.  This could be done by adding a few fields to the dialog box where we provide the path to the CSV and the template.

**Comment by SvenWerlen** [comment]
Available in version `1.3.0+`
![import-data](https://user-images.githubusercontent.com/938060/92982336-babf5200-f46b-11ea-8005-fad9b82f51c9.jpg)
