### ISSUE TITLE
Issue: Text Characters That Don't Import

### ISSUE THREAD

**Issue by mparker546** [SvenWerlen/fvtt-data-toolbox#7]
Copying data from PDF into CSV I've found characters that don't transcribe through the Data Toolbox process and are imported as a null character (�).

![image](https://user-images.githubusercontent.com/64708616/97787409-f8914a80-1b7f-11eb-9686-092fb0d4b2d4.png)

Characters that this applies to include:
•	
–
—
…

**Comment by SvenWerlen** [comment]
Sorry for the very late reply on this issue. 
I'm not able to reproduce but I suspect that your files are using an encoding different from `utf-8`. Can you provide a sample file and a template such I can dig further.

**Comment by SvenWerlen** [comment]
I'll close this issue. Feel free to reopen it if you can reproduce the issue.
